all:
  children:
    ansible-terraform:
      hosts:
        18.205.153.240:
          ansible_user: ubuntu
          ansible_private_key_file: /home/coelho/Form_DevOps_Alura/terraform/instancia_alura.pem