all:
  children:
    ansible-terraform:
      hosts:
        44.201.143.248:
          ansible_user: ubuntu
          ansible_private_key_file: /home/coelho/Form_DevOps_Alura/terraform/instancia_alura.pem