all:
  children:
    ansible-terraform:
      hosts:
        52.91.213.160:
          ansible_user: ubuntu
          ansible_private_key_file: /home/coelho/Form_DevOps_Alura/terraform/instancia_alura.pem