- hosts: ansible-terraform
  become: yes
  tasks:
    - name: Testando conexão
      ping:
    - name: instalando o python e virtualenv
      apt:
        pkg:
          - python3
          - python3-pip
          - virtualenv
        update_cache: yes
        
    - name: criando ambiente virtual
      pip:
        virtualenv: /home/ubuntu/tcc/venv
        name: 
          - django
          - djangorestframework
        
    - name: Iniciando o servidor
      shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc/'
      args:
        chdir: /home/ubuntu/tcc
        creates: /home/ubuntu/tcc/setup  

    - name: Ajustar permissões do diretório
      file:
        path: /home/ubuntu/tcc
        owner: ubuntu
        group: ubuntu
        mode: '0755'
        recurse: yes
        
    - name: Alterando o hosts settings
      lineinfile:
        path: /home/ubuntu/tcc/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes
        
      # executable: pip3
      # state: present
      # shell: "virtualenv -p python3 venv"
      # args:
      #   chdir: /home/ubuntu/tcc/venv

      # cache_valid_time: 3600
    # - name: criando arquivo
    #   copy:
    #     dest: /home/ubuntu/index.html
    #     content: <h1>Feito com Ansible e Terraform</h1>
      
    # - name: criando o srv http
    #   shell: "nohup busybox httpd -f -p 8080 &"